name: WeedWeek
favicon: null
layout_spectrum: 0.7028610673733056
typography_spectrum: 0.42910946370102465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.004590292228385806
  lightness: 0.6528601082973182
  saturation: 0.8378990001510829
  rhythmicContrast: 0.3475767995696515
purpose: []
